### ISSUE TITLE
Create content for landing page section

### ISSUE THREAD

**Issue by PeopleOfColorCode** [PeopleOfColorCode/PeopleOfColorCode.com#10]
This entails coming up with the text for the main header section and replacing the existing text with the text that we decide on.

![image](https://user-images.githubusercontent.com/57328828/70853615-d3b3bc00-1e75-11ea-8578-3a83b9a2d2f9.png)

**Comment by grace000** [comment]
The main text will be as stated below unless we update it.

<img width="764" alt="Screen Shot 2020-03-07 at 9 30 49 AM" src="https://user-images.githubusercontent.com/21062007/76146195-69667e00-6056-11ea-8711-5985f0fc22e1.png">
